repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v2.5.0"
  hooks:
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: check-added-large-files

- repo: local
  hooks:

    - id: isort
      name: isort
      entry: isort
      files: ^(config/|file/)
      language: system
      types: [python]
      args: ["--profile", "black", --line-length=120]

    - id: flake8
      name: flake8
      entry: flake8
      files: ^(config/|file/)
      language: system
      types: [python]
      args: [--config, setup.cfg]
